-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgv6MACMWXvCFxQhLJ
kuC0HyCJ2yai2UoK/nUswZ6MoDmgCgYIKoZIzj0DAQehRANCAAT/m8Fu2U7jsTTM
OF+mgargsAdPxMHRoZaPUvhYsAA+RqaoK0YsSXhfW7KeS61/L+93GIra7V+YzRsE
T0JASxXj
-----END PRIVATE KEY-----