version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-swoole-app
    container_name: laravel-swoole-app
    restart: unless-stopped
    tty: true
    ports:
      - "9501:9501"
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    command: php artisan swoole:http start

  db:
    image: mysql:8
    container_name: mysql8
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

# Docker volumes
volumes:
  dbdata:
    driver: local

# Docker networks
networks:
  app-network:
    driver: bridge
